### PR TITLE
Change to appid used by Tahoe-LAFS invite feature

### LINKED ISSUE #49: Change magic-wormhole appid
Since `tahoe` uses the appid `tahoe-lafs.org/invite` for the `tahoe invite` command, we should switch gridsync (in concert with S4) to use that same appid by default. See https://github.com/LeastAuthority/leastauthority.com/issues/705

### PR DESCRIPTION
**Pull request by exarkun**
Fixes #49 

I wasn't sure if it made more sense to make this PR against `master` or `dev`.  Let me know if you want me to re-do it against `dev`.  Or to do a follow-up duplicating it against `dev`?

### CODE REVIEW

**Comment by exarkun** [comment]
Oh.  Also I was confused by the two different `config.txt` files.

**Comment by crwood** [comment]
This was already addressed last week by [dd0aa47](https://github.com/gridsync/gridsync/commit/dd0aa472e5b879e16cf8808db088358fa73bda64) -- thanks though!

I'll update the build scripts in the meantime to do away with the additional `config.txt` in the rootdir (which is copied to `gridsync/resources` at build time but isn't really necessary anymore).

**Comment by exarkun** [comment]
What's the workflow for issues?  When does #49 get closed?

**Comment by crwood** [comment]
Github should automatically close #49 once `dev` gets merged to `master`, however, I will manually close it right now just to reduce confusion.

**Pull request closed without merging**
