### PR TITLE
Exit handling subprocess pidfiles

### PR DESCRIPTION
**Pull request by meejah**
There is an appropriate magic-folder release (22.10.0) but not yet for Tahoe-LAFS (using https://github.com/tahoe-lafs/tahoe-lafs/pull/1221 would work).

### CODE REVIEW

**Comment by meejah** [comment]
I was hoping that Nix would "fix itself" once the cache or whatever updated. I don't know why it's not finding https://pypi.org/project/magic-folder/22.10.0/

**Comment by exarkun** [comment]
> I was hoping that Nix would "fix itself" once the cache or whatever updated. I don't know why it's not finding https://pypi.org/project/magic-folder/22.10.0/

We don't let dependencies float in the Nix build environment.  If we want to see updates, we have to ask explicitly:

```
[exarkun@magnon:~/Work/python/tahoe-lafs]$ niv show pypi-deps-db
INFO: new sources.nix available: 24 -> 27
  Please run 'niv init' or add the following line in the nix/sources.nix file:
  # niv: no_update
pypi-deps-db
  branch: master
  description: Probably the most complete python dependency database
  homepage: 
  owner: DavHau
  repo: pypi-deps-db
  rev: 76b8f1e44a8ec051b853494bcf3cc8453a294a6a
  sha256: 18fgqyh4z578jjhk26n1xi2cw2l98vrqp962rgz9a6wa5yh1nm4x
  type: tarball
  url: https://github.com/DavHau/pypi-deps-db/archive/76b8f1e44a8ec051b853494bcf3cc8453a294a6a.tar.gz
  url_template: https://github.com/<owner>/<repo>/archive/<rev>.tar.gz

[exarkun@magnon:~/Work/python/tahoe-lafs]$ niv update pypi-deps-db
Update pypi-deps-db
  INFO: new sources.nix available: 24 -> 27
    Please run 'niv init' or add the following line in the nix/sources.nix file:
    # niv: no_update
Done: Update pypi-deps-db

[exarkun@magnon:~/Work/python/tahoe-lafs]$ niv show pypi-deps-db
INFO: new sources.nix available: 24 -> 27
  Please run 'niv init' or add the following line in the nix/sources.nix file:
  # niv: no_update
pypi-deps-db
  branch: master
  description: Probably the most complete python dependency database
  homepage: 
  owner: DavHau
  repo: pypi-deps-db
  rev: 2505eb53d85cd727c87611ee4aa35152821a12b2
  sha256: 0nhl0rzlp4fgzxb15pmnq14d0rzcwhvwn40vx7fnk41z9gwxcp4c
  type: tarball
  url: https://github.com/DavHau/pypi-deps-db/archive/2505eb53d85cd727c87611ee4aa35152821a12b2.tar.gz
  url_template: https://github.com/<owner>/<repo>/archive/<rev>.tar.gz
```

I can push this change if you want or you can reproduce it with https://github.com/nmattia/niv and `niv update pypi-deps-db --rev 2505eb53d85cd727c87611ee4aa35152821a12b2`.

**Comment by meejah** [comment]
@exarkun if you have the appropriate NixOS change handy, it would be great to push it here in the interests of time .. my nix setup isn't letting me install `niv`.

**Comment by exarkun** [comment]
So apparently I thought I was commenting on a tahoe-lafs issue above.  Gridsync has a Nix Flake now so actually I'm running `nix flake lock --update-input pypi-deps-db`.  Nix Flakes are the new thing so ideally any projects we have that are still using Niv will at some point switch to this workflow.

I'm pushing the update now.

**Comment by crwood** [comment]
Thank you  so much for all of your work on this, @meejah; merging...

**Pull request merged**
